// Наследовать: IHTMLDOMNode {HTMLFile}
// Наследовать: IHTMLElement {HTMLFile}, IHTMLElement2 {HTMLFile}, IHTMLElement3 {HTMLFile}, IHTMLElement4 {HTMLFile}, IHTMLElement5 {HTMLFile}
// Наследовать: IHTMLAnchorElement {HTMLFile}, IHTMLAreaElement {HTMLFile}, IHTMLAudioElement {HTMLFile}, IHTMLBaseElement {HTMLFile}, IHTMLBodyElement {HTMLFile}, IHTMLBRElement {HTMLFile}, IHTMLButtonElement {HTMLFile}, IHTMLCanvasElement {HTMLFile}, IHTMLDataElement {HTMLFile}, IHTMLDataListElement {HTMLFile}, IHTMLDetailsElement {HTMLFile}, IHTMLDialogElement {HTMLFile}, IHTMLDivElement {HTMLFile}, IHTMLDListElement {HTMLFile}, IHTMLEmbedElement {HTMLFile}, IHTMLFieldSetElement {HTMLFile}, IHTMLFormElement {HTMLFile}, IHTMLHeadElement {HTMLFile}, IHTMLHeadingElement {HTMLFile}, IHTMLHRElement {HTMLFile}, IHTMLHtmlElement {HTMLFile}, IHTMLIFrameElement {HTMLFile}, IHTMLImageElement {HTMLFile}, IHTMLInputElement {HTMLFile}, IHTMLLabelElement {HTMLFile}, IHTMLLegendElement {HTMLFile}, IHTMLLIElement {HTMLFile}, IHTMLLinkElement {HTMLFile}, IHTMLMapElement {HTMLFile}, IHTMLMediaElement {HTMLFile}, IHTMLMetaElement {HTMLFile}, IHTMLMeterElement {HTMLFile}, IHTMLModElement {HTMLFile}, IHTMLObjectElement {HTMLFile}, IHTMLOListElement {HTMLFile}, IHTMLOptGroupElement {HTMLFile}, IHTMLOptionElement {HTMLFile}, IHTMLOutputElement {HTMLFile}, IHTMLParagraphElement {HTMLFile}, IHTMLParamElement {HTMLFile}, IHTMLPictureElement {HTMLFile}, IHTMLPreElement {HTMLFile}, IHTMLProgressElement {HTMLFile}, IHTMLQuoteElement {HTMLFile}, IHTMLScriptElement {HTMLFile}, IHTMLSelectElement {HTMLFile}, IHTMLSlotElement {HTMLFile}, IHTMLSourceElement {HTMLFile}, IHTMLSpanElement {HTMLFile}, IHTMLStyleElement {HTMLFile}, IHTMLTableCaptionElement {HTMLFile}, IHTMLTableCellElement {HTMLFile}, IHTMLTableColElement {HTMLFile}, IHTMLTableElement {HTMLFile}, IHTMLTableRowElement {HTMLFile}, IHTMLTableSectionElement {HTMLFile}, IHTMLTemplateElement {HTMLFile}, IHTMLTextAreaElement {HTMLFile}, IHTMLTimeElement {HTMLFile}, IHTMLTitleElement {HTMLFile}, IHTMLTrackElement {HTMLFile}, IHTMLUListElement {HTMLFile}, IHTMLVideoElement
                 
Перем firstChild Экспорт; // ОбработкаОбъект.ирТипHTMLElement
Перем lastChild Экспорт; // ОбработкаОбъект.ирТипHTMLElement
Перем parentElement Экспорт; // ОбработкаОбъект.ирТипHTMLElement

Процедура scrollIntoViewIfNeeded() Экспорт 
КонецПроцедуры   